---
homeassistant_enabled: false
homeassistant_available_externally: false

# directories
homeassistant_data_directory: "{{ docker_home }}/homeassistant"

# network
homeassistant_port: "8123"
homeassistant_hostname: "homeassistant"

# docker
homeassistant_container_name: "homeassistant"
homeassistant_image_name: "homeassistant/home-assistant"
homeassistant_image_version: latest

homeassistant_zwavejs_container_name: "homeassistant_zwavejs"
homeassistant_zwavejs_image_name: "zwavejs/zwave-js-ui"
homeassistant_zwavejs_image_version: latest

# specs
homeassistant_memory: 1g

homeassistant_zwave_device_id: unset
homeassistant_zigbee_device_id: unset
